apiVersion: v2
name: rocketchat
description: Prepare to take off with the ultimate chat platform, experience the next level of team communications
version: 1.0.2
appVersion: 3.13.2
keywords:
- chat
- communication
- http
- web
- application
- nodejs
- javascript
- meteor
home: https://rocket.chat/
icon: https://raw.githubusercontent.com/RocketChat/Rocket.Chat.Artwork/master/Logos/icon.svg
sources:
- https://github.com/RocketChat/Docker.Official.Image/
dependencies:
- name: mongodb
  version: 10.3.x
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled