
{{- if gt ( .Values.replicaCount | int ) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "helm-rocketchat.labels" . | nindent 4 }}
  name: {{ template "helm-rocketchat.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "helm-rocketchat.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.minAvailable }}
{{- end }}